# https://taskfile.dev

version: "3"

silent: true

vars:
  ORG: lay3rlabs
  IMAGE_NAME: wasi-builder
  REGISTRY: ghcr.io
  DOCKERFILE: Dockerfile
  RUST_VERSION: 1.90-slim-bookworm
  CARGO_COMPONENT_VERSION: 0.21.1
  WASM_TOOLS_VERSION: 1.238.1
  WKG_VERSION: 0.12.0

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  build:
    desc: Build Docker image
    preconditions:
      - sh: test "{{OS}}" = "linux"
        msg: "This task can only run on Linux (current OS: {{OS}})"
    vars:
      IS_LOCAL: '{{.IS_LOCAL | default "true"}}'
      VERSION: '{{.VERSION | default "latest"}}'
    cmds:
      - |
        # Check if version is a git hash (7 characters, alphanumeric)
        if [[ "{{.VERSION}}" =~ ^[a-f0-9]{7}$ ]]; then
          TAGS="--tag {{.REGISTRY}}/{{.ORG}}/{{.IMAGE_NAME}}:{{.VERSION}} --tag {{.REGISTRY}}/{{.ORG}}/{{.IMAGE_NAME}}:latest"
        else
          TAGS="--tag {{.REGISTRY}}/{{.ORG}}/{{.IMAGE_NAME}}:{{.VERSION}}"
        fi

        if [ "{{.IS_LOCAL}}" = "true" ]; then
          # For local builds, use current architecture
          PLATFORM_FLAG="--platform {{OS}}/{{ARCH}}"
          LOAD_FLAG="--load"
          PUSH_FLAG=""
        else
          # For remote builds, use multi-platform
          PLATFORM_FLAG="--platform {{OS}}/amd64,{{OS}}/arm64"
          LOAD_FLAG=""
          PUSH_FLAG="--push"
        fi

        docker buildx build \
          $PLATFORM_FLAG \
          $TAGS \
          --build-arg RUST_VERSION={{.RUST_VERSION}} \
          --build-arg CARGO_COMPONENT_VERSION={{.CARGO_COMPONENT_VERSION}} \
          --build-arg WASM_TOOLS_VERSION={{.WASM_TOOLS_VERSION}} \
          --build-arg WKG_VERSION={{.WKG_VERSION}} \
          $LOAD_FLAG \
          $PUSH_FLAG \
          -f {{.DOCKERFILE}} docker

  setup-buildx:
    desc: Setup and use docker buildx builder
    cmds:
      - docker buildx create --name multiarch --driver docker-container --use || true
      - docker buildx inspect --bootstrap

  clean:
    desc: Clean up buildx builder
    cmds:
      - docker buildx rm multiarch || true

  test:
    desc: Test the built Docker image
    vars:
      VERSION: '{{.version | default "latest"}}'
      TEST_DIR: /tmp/wasi-test
    cmds:
      - task: test:setup
        vars:
          TEST_DIR: "{{.TEST_DIR}}"
      - task: test:run
        vars:
          TEST_DIR: "{{.TEST_DIR}}"
          VERSION: "{{.VERSION}}"
      - task: test:verify
        vars:
          TEST_DIR: "{{.TEST_DIR}}"
      - defer: rm -rf "{{.TEST_DIR}}"
      - echo "✅ Test completed successfully!"

  test:setup:
    desc: Setup test environment
    requires:
      vars: [TEST_DIR]
    cmds:
      - rm -rf {{.TEST_DIR}}
      - mkdir -p {{.TEST_DIR}}/output
      - mkdir -p {{.TEST_DIR}}/templates/src
      - mkdir -p {{.TEST_DIR}}/templates/wit
      - |
        cat > {{.TEST_DIR}}/templates/src/lib.rs << 'EOF'
        #[no_mangle]
        pub extern "C" fn greet() -> *const u8 {
            let message = "Hello from WASI component!";
            message.as_ptr()
        }
        EOF
      - |
        cat > {{.TEST_DIR}}/templates/wit/world.wit << 'EOF'
        package test:component;

        world hello {
            export greet: func() -> string;
        }
        EOF
      - |
        cat > {{.TEST_DIR}}/templates/Cargo.toml << 'EOF'
        [package]
        name = "test-component"
        version = "0.1.0"
        edition = "2021"

        [lib]
        crate-type = ["cdylib"]

        [dependencies]

        [package.metadata.component]
        package = "test:component"
        EOF
      - cd {{.TEST_DIR}} && cargo init --name test-component --lib && cp -r templates/* . && cargo generate-lockfile

  test:run:
    desc: Run the Docker container
    requires:
      vars: [TEST_DIR, VERSION]
    cmds:
      - >
        docker run --rm -v {{.TEST_DIR}}:/docker/test-component
        -v {{.TEST_DIR}}/output:/docker/output
        {{.REGISTRY}}/{{.ORG}}/{{.IMAGE_NAME}}:{{.VERSION}}
        test-component
        --out-dir /docker/output
      - chown -R $(id -u):$(id -g) {{.TEST_DIR}}/output 2>/dev/null || true

  test:verify:
    desc: Verify test results
    requires:
      vars: [TEST_DIR]
    cmds:
      - |
        if [ -f "{{.TEST_DIR}}/output/test_component.wasm" ]; then
          echo "✅ WASM file created successfully"
          ls -lh {{.TEST_DIR}}/output/test_component.wasm
          file {{.TEST_DIR}}/output/test_component.wasm | grep -q "WebAssembly" && echo "✅ WASM file is valid" || (echo "❌ WASM file is not valid" && exit 1)
        else
          echo "❌ Test FAILED: WASM file not found"
          ls -la {{.TEST_DIR}}/output/
          exit 1
        fi
